### ISSUE TITLE
KeyError: 'physical'

### ISSUE THREAD

**Issue by maginna** [boldport/release4-example#1]
Failed build utils.py
n getSurfaceLayers
    board_stackup = config.brd['physical'].get('stackup')
KeyError: 'physical'

Added to release4-example.json 
  "physical": {
      "stackup": [
        "top",
        "bottom"
    ]
  },
Passed that and then failed in footprint.py
line 152, in _processPins
    self._shapes[stype][layer].append(sshape)
KeyError: u'internal
edited via.json
"layers": ["top", "internal","bottom"], to "layers": ["top","bottom"],
then it built.

**Comment by saardrimer** [comment]
Are you using branch 'release4' of PCBmodE with this design?

**Comment by maginna** [comment]
First day at school, I upgraded an older release to the new default.  With rel 4 the example works fine, on OS X 10.9.5. Apologies. Thank you.

**Comment by saardrimer** [comment]
Awesome! Keep posting problems and show off what you're making ;)
